name: Download Artifact Pipeline

on:
  workflow_run:
    workflows: ["Build, Test & Store Artifact"]
    types:
      - completed

jobs:
  download:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show artifact
        run: ls -R
